name: Github

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Pokemon Api 출력하기
        run: echo "Pokemon Api"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
          pwd

      - name: Github Actions 자체 저장되어 있는 변수 사용하기
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secret.MY_NAME }}
          echo ${{ secret.MY_HOBBY }}
